using log4net;
using MetaGeta;
using MetaGeta.Browser;
using MetaGeta.DataStore;
using MetaGeta.GUI;
using MetaGeta.Utilities;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Shapes;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MetaGeta.GUI.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaGeta.GUI.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		static internal System.Drawing.Icon MetaGeta_Icon {
			get {
				object obj = ResourceManager.GetObject("MetaGeta_Icon", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		static internal System.Drawing.Bitmap MetaGeta_Image {
			get {
				object obj = ResourceManager.GetObject("MetaGeta_Image", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
